arrays: hw2_p1.c
	gcc -Wall -Wextra -Pedantic -o arrays hw2_p1.c

check: hw2_p2.c
	gcc -Wall -Wextra -Pedantic -o check hw2_p2.c

sinsquare: hw2_p3.c my_abs.c
	gcc -Wall -Wextra -Pedantic -lm -o sinsquare hw2_p3.c
