powers: hw3_p1.c
	gcc -o powers -Wall -Wextra -pedantic -lm hw3_p1.c

concat: hw3_p2.c
	gcc -o concat -Wall -Wextra -pedantic -lm hw3_p2.c

rgbf: hw3_p3.c
	gcc -o rgbf -Wall -Wextra -pedantic -lm hw3_p3.c

paths: hw3_p4.c
	gcc -o paths -Wall -Wextra -pedantic -lm hw3_p4.c
