p1: euler_p1.c
	gcc -Wall -Wextra -Pedantic -o p1 euler_p1.c
p2: euler_p2.c
	gcc -Wall -Wextra -Pedantic -o p2 euler_p2.c
p3: euler_p3.c
	gcc -Wall -Wextra -Pedantic -o p3 euler_p3.c
p4: euler_p4.c
	gcc -Wall -Wextra -Pedantic -o p4 euler_p4.c
p5: euler_p5.c
	gcc -Wall -Wextra -Pedantic -o p5 euler_p5.c
p6: euler_p6.c
	gcc -Wall -Wextra -Pedantic -o p6 euler_p6.c
p7: euler_p7.c
	gcc -Wall -Wextra -Pedantic -o p7 euler_p7.c
p8: euler_p8.c
	gcc -Wall -Wextra -Pedantic -o p8 euler_p8.c
p9: euler_p9.c
	gcc -Wall -Wextra -Pedantic -o p9 euler_p9.c
p10: euler_p10.c
	gcc -Wall -Wextra -Pedantic -o p10 euler_p10.c
p11: euler_p11.c
	gcc -Wall -Wextra -Pedantic -o p11 euler_p11.c
p12: euler_p12.c
	gcc -Wall -Wextra -Pedantic -o p12 euler_p12.c
p13: euler_p13.c
	gcc -Wall -Wextra -Pedantic -o p13 euler_p13.c
p14: euler_p14.c
	gcc -Wall -Wextra -Pedantic -o p14 euler_p14.c
p15: euler_p15.c
	gcc -Wall -Wextra -Pedantic -o p15 euler_p15.c
p16: euler_p16.c
	gcc -Wall -Wextra -Pedantic -o p16 euler_p16.c
p17: euler_p17.c
	gcc -Wall -Wextra -Pedantic -o p17 euler_p17.c
p18: euler_p18.c
	gcc -Wall -Wextra -Pedantic -o p18 euler_p18.c
p19: euler_p19.c
	gcc -Wall -Wextra -Pedantic -o p19 euler_p19.c
p20: euler_p20.c
	gcc -Wall -Wextra -Pedantic -o p20 euler_p20.c
p21: euler_p21.c
	gcc -Wall -Wextra -Pedantic -o p21 euler_p21.c
p22: euler_p22.c
	gcc -Wall -Wextra -Pedantic -o p22 euler_p22.c
p23: euler_p23.c
	gcc -Wall -Wextra -Pedantic -o p23 euler_p23.c
p24: euler_p24.c
	gcc -Wall -Wextra -Pedantic -o p24 euler_p24.c
p25: euler_p25.c
	gcc -Wall -Wextra -Pedantic -o p25 euler_p25.c
p26: euler_p26.c
	gcc -Wall -Wextra -Pedantic -o p26 euler_p26.c
p27: euler_p27.c
	gcc -Wall -Wextra -Pedantic -o p27 euler_p27.c
p28: euler_p28.c
	gcc -Wall -Wextra -Pedantic -o p28 euler_p28.c
p29: euler_p29.c
	gcc -Wall -Wextra -Pedantic -o p29 euler_p29.c
p30: euler_p30.c
	gcc -Wall -Wextra -Pedantic -o p30 euler_p30.c
p31: euler_p31.c
	gcc -Wall -Wextra -Pedantic -o p31 euler_p31.c
p32: euler_p32.c
	gcc -Wall -Wextra -Pedantic -o p32 euler_p32.c
p33: euler_p33.c
	gcc -Wall -Wextra -Pedantic -o p33 euler_p33.c
p34: euler_p34.c
	gcc -Wall -Wextra -Pedantic -o p34 euler_p34.c
p35: euler_p35.c
	gcc -Wall -Wextra -Pedantic -o p35 euler_p35.c
p36: euler_p36.c
	gcc -Wall -Wextra -Pedantic -o p36 euler_p36.c
p37: euler_p37.c
	gcc -Wall -Wextra -Pedantic -o p37 euler_p37.c
p38: euler_p38.c
	gcc -Wall -Wextra -Pedantic -o p38 euler_p38.c
p39: euler_p39.c
	gcc -Wall -Wextra -Pedantic -o p39 euler_p39.c
p40: euler_p40.c
	gcc -Wall -Wextra -Pedantic -o p40 euler_p40.c
p41: euler_p41.c
	gcc -Wall -Wextra -Pedantic -o p41 euler_p41.c
p42: euler_p42.c
	gcc -Wall -Wextra -Pedantic -o p42 euler_p42.c
p43: euler_p43.c
	gcc -Wall -Wextra -Pedantic -o p43 euler_p43.c
p44: euler_p44.c
	gcc -Wall -Wextra -Pedantic -o p44 euler_p44.c
p45: euler_p45.c
	gcc -Wall -Wextra -Pedantic -o p45 euler_p45.c
p46: euler_p46.c
	gcc -Wall -Wextra -Pedantic -o p46 euler_p46.c
p47: euler_p47.c
	gcc -Wall -Wextra -Pedantic -o p47 euler_p47.c
p48: euler_p48.c
	gcc -Wall -Wextra -Pedantic -o p48 euler_p48.c
p49: euler_p49.c
	gcc -Wall -Wextra -Pedantic -o p49 euler_p49.c
p50: euler_p50.c
	gcc -Wall -Wextra -Pedantic -o p50 euler_p50.c
p51: euler_p51.c
	gcc -Wall -Wextra -Pedantic -o p51 euler_p51.c
p52: euler_p52.c
	gcc -Wall -Wextra -Pedantic -o p52 euler_p52.c
p53: euler_p53.c
	gcc -Wall -Wextra -Pedantic -o p53 euler_p53.c
p54: euler_p54.c
	gcc -Wall -Wextra -Pedantic -o p54 euler_p54.c
p55: euler_p55.c
	gcc -Wall -Wextra -Pedantic -o p55 euler_p55.c
p56: euler_p56.c
	gcc -Wall -Wextra -Pedantic -o p56 euler_p56.c
p57: euler_p57.c
	gcc -Wall -Wextra -Pedantic -o p57 euler_p57.c
p58: euler_p58.c
	gcc -Wall -Wextra -Pedantic -o p58 euler_p58.c
p59: euler_p59.c
	gcc -Wall -Wextra -Pedantic -o p59 euler_p59.c
p60: euler_p60.c
	gcc -Wall -Wextra -Pedantic -o p60 euler_p60.c
p61: euler_p61.c
	gcc -Wall -Wextra -Pedantic -o p61 euler_p61.c
p62: euler_p62.c
	gcc -Wall -Wextra -Pedantic -o p62 euler_p62.c
p63: euler_p63.c
	gcc -Wall -Wextra -Pedantic -o p63 euler_p63.c
p64: euler_p64.c
	gcc -Wall -Wextra -Pedantic -o p64 euler_p64.c
p65: euler_p65.c
	gcc -Wall -Wextra -Pedantic -o p65 euler_p65.c
p66: euler_p66.c
	gcc -Wall -Wextra -Pedantic -o p66 euler_p66.c
p67: euler_p67.c
	gcc -Wall -Wextra -Pedantic -o p67 euler_p67.c
p68: euler_p68.c
	gcc -Wall -Wextra -Pedantic -o p68 euler_p68.c
p69: euler_p69.c
	gcc -Wall -Wextra -Pedantic -o p69 euler_p69.c
p70: euler_p70.c
	gcc -Wall -Wextra -Pedantic -o p70 euler_p70.c
p71: euler_p71.c
	gcc -Wall -Wextra -Pedantic -o p71 euler_p71.c
p72: euler_p72.c
	gcc -Wall -Wextra -Pedantic -o p72 euler_p72.c
p73: euler_p73.c
	gcc -Wall -Wextra -Pedantic -o p73 euler_p73.c
p74: euler_p74.c
	gcc -Wall -Wextra -Pedantic -o p74 euler_p74.c
p75: euler_p75.c
	gcc -Wall -Wextra -Pedantic -o p75 euler_p75.c
p76: euler_p76.c
	gcc -Wall -Wextra -Pedantic -o p76 euler_p76.c
p77: euler_p77.c
	gcc -Wall -Wextra -Pedantic -o p77 euler_p77.c
p78: euler_p78.c
	gcc -Wall -Wextra -Pedantic -o p78 euler_p78.c
p79: euler_p79.c
	gcc -Wall -Wextra -Pedantic -o p79 euler_p79.c
p80: euler_p80.c
	gcc -Wall -Wextra -Pedantic -o p80 euler_p80.c
p81: euler_p81.c
	gcc -Wall -Wextra -Pedantic -o p81 euler_p81.c
p82: euler_p82.c
	gcc -Wall -Wextra -Pedantic -o p82 euler_p82.c
p83: euler_p83.c
	gcc -Wall -Wextra -Pedantic -o p83 euler_p83.c
p84: euler_p84.c
	gcc -Wall -Wextra -Pedantic -o p84 euler_p84.c
p85: euler_p85.c
	gcc -Wall -Wextra -Pedantic -o p85 euler_p85.c
p86: euler_p86.c
	gcc -Wall -Wextra -Pedantic -o p86 euler_p86.c
p87: euler_p87.c
	gcc -Wall -Wextra -Pedantic -o p87 euler_p87.c
p88: euler_p88.c
	gcc -Wall -Wextra -Pedantic -o p88 euler_p88.c
p89: euler_p89.c
	gcc -Wall -Wextra -Pedantic -o p89 euler_p89.c
p90: euler_p90.c
	gcc -Wall -Wextra -Pedantic -o p90 euler_p90.c
p91: euler_p91.c
	gcc -Wall -Wextra -Pedantic -o p91 euler_p91.c
p92: euler_p92.c
	gcc -Wall -Wextra -Pedantic -o p92 euler_p92.c
p93: euler_p93.c
	gcc -Wall -Wextra -Pedantic -o p93 euler_p93.c
p94: euler_p94.c
	gcc -Wall -Wextra -Pedantic -o p94 euler_p94.c
p95: euler_p95.c
	gcc -Wall -Wextra -Pedantic -o p95 euler_p95.c
p96: euler_p96.c
	gcc -Wall -Wextra -Pedantic -o p96 euler_p96.c
p97: euler_p97.c
	gcc -Wall -Wextra -Pedantic -o p97 euler_p97.c
p98: euler_p98.c
	gcc -Wall -Wextra -Pedantic -o p98 euler_p98.c
p99: euler_p99.c
	gcc -Wall -Wextra -Pedantic -o p99 euler_p99.c
p100: euler_p100.c
	gcc -Wall -Wextra -Pedantic -o p100 euler_p100.c
